using System;
using UnityEngine;
using UnityEditor;

namespace Mona
{
    // Quailty Checks that run both in editor and in private-build
    public static class QualityAssurance
    {

        // Is a list of error codes generated by the space.
        public static string[] ErrorCodes;

        // Run QA check
        public static void CheckQuality()
        {

        }

        // Ensure that Space, PortalLayer, ArtifactLayer scenes exist.
        // Code BAD_SPACE_SCENE_SETUP
        public static void TestSceneExistance()
        {
            
        }

        // Enshure so each scene has one game object tagged as the layer.
        // Code BAD_LAYER_TAG
        public static string TestLayerExistance()
        {

            return "";
        }
    }
}